baseURL = 'https://abhinandhs.in/'
languageCode = 'en-us'
title = 'Abhinandh S'

theme = 'lugo'

cleanDestinationDir = true


[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    style = 'catppuccin-mocha'
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
