title = 'Abhinandh S'
baseURL = 'https://abhinandhs.in/'
languageCode = 'en-us'
copyright = '© 2024-25 Abhinandh S.'
# theme = 'iris'
favicon = "/favicon.ico"
cleanDestinationDir = true
enableRobotsTXT = true

[params]
  relatedtext = "Related tags"
  favicon = "/favicon.ico"
  #list items
  datesinlist = true
  authorsinlist = true
  #footer items
  nextprev = true
  taglist = true
  showrss = true
  showemail = true
  showgithub = true
  showx = true
  
[markup]
  [markup.highlight]
    hl_Lines = '0'
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    style = 'onedark' # catppuccin-mocha  tokyonight-night
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
