title = "Abhinandh S"
baseURL = 'https://abhi-xyz.github.io/'
languageCode = 'en-us'

[params]
  # "relatedtext" is the text that appears above the tag list at the bottom of pages.
  relatedtext = "Related"
  favicon = "/favicon.ico"

  #list items
  datesinlist = true
  authorsinlist = true

  #footer items
  nextprev = true
  taglist = true
  showrss = true
  showemail = true
  showgithub = true
  showx = true
